### PR TITLE
Update model-config.yaml

### PR DESCRIPTION
**Pull request by LeonardRanaldi**
LLaMA configuration

### CODE REVIEW

**Comment by LeonardRanaldi** [comment]
Hi,
My tool can use Llama model.
Best,
Leonardo.


Il lun 26 giu 2023, 16:43 Dongximing ***@***.***> ha scritto:

**Comment by Dongximing** [comment]
Hi Leonard 
Thank for you your reply me, 
and I saw your branch and see you just add :

decapoda-research/llama-7b-hf:
```
    embedding: "transformer.embed_tokens.weight"
    type: 'causal'
    activations:
    - 'mlp\.up_proj'
    token_prefix: '▁'
    partial_token_prefix: ''
```


in the ymal file,  

I just wondering is that all you modified?

Thanks 
Ximing

**Comment by LeonardRanaldi** [comment]
Hi,
Yes, it is.

Il lun 26 giu 2023, 21:07 Dongximing ***@***.***> ha scritto:

**Comment by jalammar** [comment]
Does the library work with the model after this addition? Should we merge?

**Pull request closed without merging**
