### PR TITLE
Memory management and tweaks

### PR DESCRIPTION
**Pull request by nostalgebraist**
Hello Jay, thanks for all your work on GPT interpretation!

This PR contains changes I made in a personal fork while attempting to use `ecco` with a 1.5B-size GPT-2 model.  There are 3 kinds of changes:

1. Attempts to plug memory leaks / otherwise reduce memory footprint
2. Bug fixes
3. Usability tweaks and new features

In retrospect, I wish I had made distinct branches for these 3 types of change, as together they now make up a pretty large PR.  I can still go back and do that, if (say) you want to merge the bug fixes without the other ones.

----

Context: I am using `ecco` on a 1.5B-size GPT-2 model, using a Tesla T4 GPU (~15GB memory) on Colab.

I am using version 3.4.0 of `transformers`, which is the max version consistent with ecco's `setup.py` and hence the one I got on installation. 

**1.** Memory management

Running `lm.generate` with this large model, I ran out of GPU memory.  This surprised me, because memory has not been an issue for me using the same model in tensorflow.

After looking into it, I found a few places where use of GPU memory could be lowered:

- `past`, which we don't use here, was still being computed on each step.
  - More importantly, python garbage collection was not (as far as I could tell) freeing the values of `past` produced on previous steps, so generating N tokens required enough memory to store the N pasts emitted from steps 1, 2, ..., N.
  - Mitigation: pass `use_cache=False` to the model's forward pass, so it doesn't return pasts
- Saliency calculations all used `retain_graph=True`, so the backward graphs were never cleared.
  - Mitigation: when we do several gradient calculations per step, pass `retain_graph=False` to the last one
- `hidden_states` were stored on the GPU during generation.
  - They don't need to be on the GPU at that time (because they aren't used in generation).
  - And, since we have a low CPU memory footprint otherwise, we have plenty of CPU memory to store them in.
  - Mitigation: call `.cpu()` on hidden states emitted from each step.  If we want to calculate with them later on, move them back to `self.device`.
- (Minor) Memory allocated for logit matrices from each step was not freed after sampling
  - Mitigation: `output['logits']=None` after rolling a sample

With these changes, I can run `lm.generate` for many 100s of steps, where previously I could only manage a small number, maybe ~10.

----

**2.** Bug fixes

- `activations_dict_to_array` would fail in the edge case where we only have a single token in the prompt.
  - Issue: `np.squeeze` would wrongly eliminate the position axis (because its size was 1).
  - Mitigation: use `np.concatenate`, which doesn't add an unwanted singleton dimension, so we don't have to squeeze
- top-p sampling did not work
  - Issue: `top_k_top_p_filtering` apparently expects a position axis in its input, even if that axis only has length 1
  - Mitigation: replace `[-1, :]` with `[-1: ,:]` and then squeeze after rolling a sample

----

**3.** Usability tweaks and new features

- Added an option to not track hidden_states.  This feels consistent with the way you can choose whether or not to track other things (activations, attn).
  - To help this work properly, switched from position-based indexing into the `CausalLMOutputWithPast` objects to key lookup, so we're robust to changes in the length/order of these objects.
- Added the option to only track hidden states for a user-defined subset of layers, through the new kwarg `collect_activations_layer_nums`.
  - This is valuable with a large model where you may be only interested in a specific layer, and storing activations from all layers has high memory cost.
  - `NMF` now takes this kwarg and (if not None) uses it to map between row indices in `activations` and actual layer numbers.  For example, if we are tracking layers 7 and 23, we will have an activation matrix with 2 rows.  If passed `from_layer=7, to_layer=8`, we should retrieve the row slice `[:1, :]`, not `[7:8, :]`.

----

I realize this PR is unwieldy -- I just wanted to get my changes up in some form, since at least some of them seemed unambiguously helpful (bug fixes).

Let me know if you want me to break it down into smaller pieces, or if it needs other work, or if it is generally unhelpful for your goals, or whatever.

Did not run `tox` tests because I could not get them to run properly on my machine, even after downloading the `tox.ini` from one of the CI-related branches.

### CODE REVIEW

**Comment by jalammar** [comment]
Thanks @nostalgebraist! This looks awesome! I reviewed the majority of the PR and will be revisiting a couple of pieces later. The memory tweaks, bug fixes, and features are awesome to have! I'm stoked about more robust GPT2 and GPT2-XL support as I, too, was getting out of memory when dealing with them.

I've created a v0.0.11 branch and will be merging this into it.

**Comment by jalammar** [comment]
Good thing is most tests pass, but one fails on dimensions of activations: https://github.com/jalammar/ecco/runs/1605209475

I've also changed the settings so pullrequests now trigger the test.

**Comment by nostalgebraist** [comment]
> Good thing is most tests pass, but one fails on dimensions of activations: https://github.com/jalammar/ecco/runs/1605209475. Could you please check it out?
> As far as I can gather it's because of the changes to activations_dict_to_array. There's still an unwanted singleton dimensions after the np.squeeze => np.concatenate switch, it seems?
> 
> I've also changed the settings so pullrequests now trigger the test.

I believe this is a problem with the test.  Specifically, it constructs an input to `activations_dict_to_array` which has 1 more singleton dimension than we actually see in practice.

Here's a code example showing what I mean:

```python
import numpy as np
import ecco
from ecco.lm import activations_dict_to_array

lm = ecco.from_pretrained('distilgpt2', activations=True, activations_layer_nums=[0, 1,])

output = lm.generate(text, generate=2, do_sample=True)

def show_acti_shape_per_layer(activations_dict):
  for layer_num, layer_activation_array in activations_dict.items():
    print(f"layer {layer_num}: {np.array(layer_activation_array).shape}")
  print(f"output of activations_dict_to_array: {activations_dict_to_array(activations_dict).shape}")

print("\n\nactivations_dict created by LM.generate\n")
show_acti_shape_per_layer(lm._all_activations_dict)

print("\nactivations_dict constructed in test\n")
activations_dict = {0:[[np.zeros((3,4))]],
                    1:[[np.zeros((3,4))]]}

show_acti_shape_per_layer(activations_dict)
```

which, run on this branch, will print something like the following 

```
<|endoftext|> The>> federal government
activations_dict created by LM.generate

layer 0: (1, 3, 3072)
layer 1: (1, 3, 3072)
output of activations_dict_to_array: (2, 3072, 3)

activations_dict constructed in test

layer 0: (1, 1, 3, 4)
layer 1: (1, 1, 3, 4)
output of activations_dict_to_array: (2, 3, 1, 4)
```

I'll write a change to the test.  LMK if you have any questions here.

----

Something else that I noticed while investigating: the package versions specs in `requirements.txt` do not match the ones in `setup.py`.

This could become problematic, because the tests use an environment installed from `requirements.txt`, while a user installing the package from PyPI will be installing from `setup.py`.  So, the test environment doesn't match the deployment environment.

With other packages I've worked on, what I've done is to replace the contents of `requirements.txt` with the line

`-e .`

This causes `pip install -r requirements.txt` to look at `setup.py` for what to install, making divergence impossible.  See [this post](https://caremad.io/posts/2013/07/setup-vs-requirement/) for more info.

**Comment by jalammar** [comment]
Thanks for elaborating and the new pull requests. I'll comment on each in its thread.

**Pull request merged**
